// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    TiCard: typeof import('@tiro/ui/src/card')['CardComponent']
    TiInput: typeof import('@tiro/ui/src/input')['InputComponent']
    TiSelect: typeof import('@tiro/ui/src/select')['SelectComponent']
  }
}

export { }
