// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    TiButton: typeof import('@tiro/ui/src/button')['ButtonComponent']
    TiCard: typeof import('@tiro/ui/src/card')['CardComponent']
    TiIcon: typeof import('@tiro/ui/src/icon')['IconComponent']
    TiImage: typeof import('@tiro/ui/src/image')['ImageComponent']
    TiInput: typeof import('@tiro/ui/src/input')['InputComponent']
    TiSelect: typeof import('@tiro/ui/src/select')['SelectComponent']
  }
}

export {}
