// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    TiButton: typeof import('@tiro/ui')['TiButton']
    TiCarousel: typeof import('@tiro/ui')['TiCarousel']
    TiCarouselItem: typeof import('@tiro/ui')['TiCarouselItem']
    TiIcon: typeof import('@tiro/ui')['TiIcon']
    TiInput: typeof import('@tiro/ui')['TiInput']
    TiSwitch: typeof import('@tiro/ui')['TiSwitch']
  }
}
