// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    TiIcon: typeof import('@tiro/ui/src/icon')['TiIcon']
    TiInput: typeof import('@tiro/ui/src/input')['TiInput']
  }
}
